services:
   weatherapi:
    container_name: weatherapi_container
    build: weatherapi/.
    ports:
      - "8001:8001"
   mapsapi:
    container_name: mapsapi_container
    build: mapsapi/.
    ports:
      - "8002:8002"
   posts:
    container_name: posts_container
    build: posts/.
    ports:
      - "8000:8000"
    depends_on:
      - weatherapi

   authentication:
     container_name: authentication_container
     build: authentication/.
     ports:
       - "8003:8003"
   gasapi:
     container_name: gasapi_container
     build: gasapi/.
     ports:
       - "8004:8004"
   health:
     container_name: health_container
     build: health/.
     ports:
       - "8080:8080"


volumes:
 database_mysql: