/login:
  post:
    summary: Log in to the server
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/LoginRequest'
    responses:
      200:
        description: Successfully logged in
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: JWT for the logged in user
                user:
                  $ref: '#/components/schemas/User'
                  description: User object for the logged in user
      400:
        description: Invalid credentials
      500:
        description: Internal server error