apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-deployment
  labels:
    app: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication
          image: rkogolang/repo:authentication_img
          ports:
            - containerPort: 8003
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: map-secret
                  key: jwtkey

---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  type: NodePort
  selector:
    app: authentication
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
      nodePort: 30103
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: readiness-http
spec:
  containers:
    - name: readiness
      image: registry.k8s.io/readiness
      args:
        - /server
      readinessProbe:
        httpGet:
          path: /healthz
          port: 8003
          httpHeaders:
            - name: Custom-Header
              value: Awesome
        initialDelaySeconds: 5
        periodSeconds: 10