apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-deployment
  labels:
    app: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication
          image: rkogolang/repo:authentication_img
          ports:
            - containerPort: 8003
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: map-secret
                  key: jwtkey
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8003
              httpHeaders:
                - name: Custom-Header
                  value: Awesome
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
spec:
  type: NodePort
  selector:
    app: authentication
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
      nodePort: 30103
