apiVersion: apps/v1
kind: Deployment
metadata:
  name: mapsapi-deployment
  labels:
    app: mapsapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mapsapi
  template:
    metadata:
      labels:
        app: mapsapi
    spec:
      containers:
        - name: mapsapi
          image: rkogolang/repo:mapsapi_img
          ports:
            - containerPort: 8002
          env:
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: map-secret
                key: apikey
          readinessProbe:
            httpGet:
              path: /health2
              port: 8002
              httpHeaders:
                - name: Custom-Header
                  value: Awesome
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: mapsapi-service
spec:
  type: NodePort
  selector:
    app: mapsapi
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
      nodePort: 30102
